/*  Message-number definitions derived from "ELWBIO.MSG"  */

#define BIOKEY      1
#define BIOMNU      3
#define BIOINS      4
#define BRTHDY      5
#define INVDAT      6
#define MOUTRG      7
#define DOUTRG      8
#define YOUTRG      9
#define PRPRBF     10
#define BIOHDR     11
#define LNGAGO     12
#define HDRPT2     13
#define HPYNWY     14
#define FRID13     15
#define HPPYBD     16
#define LIVONL     17
#define CNOTIL     18
#define JSTONE     19
